### ISSUE TITLE
Records with an id which are falsy (like 0 (zero)) aren't updateable

### ISSUE THREAD

**Issue by kmfdm1** [grob/ringo-pgclient#1]
client.defineModel("Todo", {
    "table": "t_todo",
    "id": {
        "column": "todo_id",
        "type": "int4",
        "constraint": "primary key"
    },
    "properties": {
        "todo": {
            "column": "tod_todo",
            "type": "varchar(512)"
        }
     }
}

// importing stuff wanting to preserve id-value (new Todo({id: 0, todo: "Buy tomados"}) would generate a new id)
client.query("insert into todos (id, todo) values (#{id}, #{todo})", { id: 0, todo: "Buy tomados"});

var t = Todo.get(0);
t.todo = "Buy Tomatos";
t.save();

Expected result:
Updated record in the database

Actual result:
Unable to read "todo_id" from undefined

**Comment by grob** [comment]
Great, thanks alot!
